# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('url', models.URLField()),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweet_search.Hashtag')),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='TweetBucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweet_search.Hashtag')),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
    ]
