# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='headline',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
